name: Privates-AddonLG
version: "${project.version}"
author: Neyuux_
main: fr.neyuux.privatesaddonlg.Plugin
description: "${project.description}"
load: STARTUP
depend : [WereWolfPlugin]
commands:
  dyson:
    description: :)
  say:
    description: Commande pour annoncer
    aliases:
      - b
      - bc
      - broadcast
    permission: say.use
  pioche:
    description: Pour avoir un meilleur minage
  dlimits:
    description: Pour changer les limites de diamants
    permission: dlimits.use