name: Privates-AddonLG
version: "${project.version}"
author: Neyuux_
main: fr.neyuux.privatesaddonlg.Plugin
description: "${project.description}"
load: STARTUP
depend : [WereWolfPlugin]
commands:
  pioche:
    description: Pour avoir un meilleur minage
  dlimits:
    description: Pour changer les limites de diamants
  don:
    description: Don pour le couple
    aliases:
      - d
      - wwdon
  neyuux:
    description: :)
  assistant:
    description: Assistant de configuration LG
    aliases:
      - assist
      - ass
      - as